#ifndef __DEBUG_PRINT_H
#define __DEBUG_PRINT_H

#define __DBG_TEMPLATE  0
#define __DBG_INIT_2D_DIGITAL_RX                    0, "DIGITAL MODEL: INIT MANUAL 2D EXPOSURE\n"
#define __DBG_INIT_2D_DIGITAL_RX_DEMO_MODE          1, "DEMO EXPOSURE\n"
#define __DBG_INIT_2D_DIGITAL_RX_STARTER_FAILURE    2, "WARNING: STARTER COMMAND FAILURE\n"
#define __DBG_INIT_2D_DIGITAL_RX_STARTER_HS_ON      3, "STARTER HS COMMAND EXECUTED\n"
#define __DBG_INIT_2D_DIGITAL_RX_STARTER_LS_ON      4, "STARTER LS COMMAND EXECUTED\n"

#define __DBG_MCC_FULL                              5, "MCC QUEUE FULL! ID=%d, BUF0=%d\n"

#define __DBG_ACTUATOR_WRONG_PARAM_TRX_HOME         6, "ACTUATORS: Wrong parameters in actuatorMoveTomoTrxHome(%d)\n"
#define __DBG_ACTUATOR_WRONG_PARAM_TRX_END          7, "ACTUATORS: Wrong parameters in actuatorMoveTomoTrxEnd(%d)\n"
#define __DBG_ACTUATOR_TRX_MOVE_COMMAND             8, "ACTUATORS: TRX MOVE COMMAND:%d\n"
#define __DBG_ACTUATOR_TRX_ZERO_COMMAND             9, "ACTUATORS: TRX ZERO SETTING COMMAND\n"
#define __DBG_ACTUATOR_TRX_QUICK_STOP_COMMAND       10,"ACTUATORS: TRX QUICK STOP COMMAND\n"
#define __DBG_ACTUATOR_TRX_BUSY                     12, "ACTUATORS: TRX BUSY\n"
#define __DBG_ACTUATOR_TRX_DISABLED_BY_PENDENA      13, "ACTUATORS: TRX DISABLED BECAUSE OF PEND-ENA SGN\n"
#define __DBG_ACTUATOR_TRX_MANUAL_MOVE_STANDARD     13, "ACTUATORS: TRX MANUAL ACTIVATION STANDARD SPEED: %d(c)\n"
#define __DBG_ACTUATOR_TRX_MANUAL_MOVE_SLOW         13, "ACTUATORS: TRX MANUAL ACTIVATION SLOW SPEED: : %d(c)\n"

#define __DBG_ACTUATOR_TRX_IDLE                     13, "ACTUATORS: TRX SET IDLE MODE\n"
#define __DBG_ACTUATOR_TRX_ACTIVATED                13, "ACTUATORS: TRX ACTIVATED\n"
#define __DBG_ACTUATOR_TRX_ZERO_ACTIVATED           13, "ACTUATORS: TRX ZERO SETTING ACTIVATED\n"

#define __DBG_ACTUATOR_TRX_ERROR                    14, "ACTUATOR: TRX ACTIVATION FAILED. ERROR=%d, SUBERR=%d, POS:%d(c)\n"
#define __DBG_ACTUATOR_TRX_COMPLETED                14, "ACTUATOR: TRX ACTIVATION COMPLETED. POS:%d(c)\n"
#define __DBG_ACTUATOR_TRX_MANUAL_COMPLETED          14, "ACTUATOR: TRX MANUAL ACTIVATION COMPLETED. POS:%d(c)\n"
#define __DBG_ACTUATOR_TRX_QUICKSTOP_COMPLETED          14, "ACTUATOR: TRX QUICK STOP COMPLETED\n"
#define __DBG_ACTUATOR_TRX_ZERO_ERROR                    14, "ACTUATOR: TRX ZERO SETTING ACTIVATION FAILED. ERROR=%d, SUBERR=%d, POS:%d(c)\n"
#define __DBG_ACTUATOR_TRX_ZERO_COMPLETED                14, "ACTUATOR: TRX ZERO SETTING ACTIVATION COMPLETED. POS:%d(c)\n"

#define __DBG_ACTUATOR_TRX_FAULT                    14, "ACTUATOR: TRX FAULT. ERRORE=%d, ERCLASS:%x, ERRNUM:%x, ERRCODE:%x , posizione=%d(c)\n"
#define __DBG_ACTUATOR_TRX_RESET_FAULT              14, "ACTUATOR: TRX REST FAULT. POS=%d(c)\n"
#define __DBG_ACTUATOR_TRX_RESET_POLLING            14, "ACTUATOR: TRX RESET POLLING\n"



#define __DBG_ACTUATOR_ARM_MOVE_COMMAND             11, "ACTUATORS: ARM MOVE COMMAND:%d\n"
#define __DBG_ACTUATOR_ARM_BUSY                     12, "ACTUATORS: ARM BUSY\n"
#define __DBG_ACTUATOR_ARM_DISABLED_BY_ROTENA       13, "ACTUATORS: ARM DISABLED BECAUSE OF ROT-ENA SGN\n"
#define __DBG_ACTUATOR_ARM_MANUAL_MODE_CMD          14, "ACTUATORS: ARM MANUAL MODE ACTIVATION: MODE=%d\n"
#define __DBG_ACTUATOR_ARM_ACTIVATED                14, "ACTUATOR: ARM AUTO MODE ACTIVATED\n"
#define __DBG_ACTUATOR_ARM_MANUAL_ACTIVATED         14, "ACTUATOR: ARM MANUAL MODE ACTIVATED\n"
#define __DBG_ACTUATOR_ARM_ERROR                    14, "ACTUATOR: ACTIVATION FAILED. ERROR=%d, SUBERR=%d\n"
#define __DBG_ACTUATOR_ARM_COMPLETED                14, "ACTUATOR: ARM ACTIVATION COMPLETED\n"
#define __DBG_ACTUATOR_ARM_MANUAL_ERROR             14, "ACTUATOR: MANUAL ACTIVATION FAILED. ERROR=%d, SUBERR=%d\n"
#define __DBG_ACTUATOR_ARM_MANUAL_COMPLETED         14, "ACTUATOR: ARM MANUAL ACTIVATION COMPLETED\n"
#define __DBG_ACTUATOR_ARM_FAULT                    14, "ACTUATOR: ARM FAULT. ERROR=%d, ERRCLASS=%d, ERRNUM=%d, ERRCODE=%d\n"
#define __DBG_ACTUATOR_ARM_RESET_FAULT              14, "ACTUATOR: ARM RESET FAULT\n"
#define __DBG_ACTUATOR_ARM_RESET_POLLING            14, "ACTUATOR: ARM RESET POLLING\n"


#define __DBG_ACTUATOR_LENZE_RUNNING                14, "ACTUATOR: LENZE RUNNING\n"
#define __DBG_ACTUATOR_LENZE_COMPLETED              14, "ACTUATOR: LENZE ACTIVATION COMPLETED\n"



#define __DEBUG_PRINT5(c,string,x1,x2,x3,x4,x5) printf(string,x1,x2,x3,x4,x5)
#define DEBUG_PRINT5(c,x1,x2,x3,x4,x5)  __DEBUG_PRINT5(c,x1,x2,x3,x4,x5)


#define __DEBUG_PRINT4(c,string,x1,x2,x3,x4) printf(string,x1,x2,x3,x4)
#define DEBUG_PRINT4(c,x1,x2,x3,x4)  __DEBUG_PRINT4(c,x1,x2,x3,x4)

#define __DEBUG_PRINT3(c,string,x1,x2,x3) printf(string,x1,x2,x3)
#define DEBUG_PRINT3(c,x1,x2,x3)  __DEBUG_PRINT3(c,x1,x2,x3)

#define __DEBUG_PRINT2(c,string,x1,x2) printf(string,x1,x2)
#define DEBUG_PRINT2(c,x1,x2)  __DEBUG_PRINT2(c,x1,x2)

#define __DEBUG_PRINT1(c,string,x1) printf(string,x1)
#define DEBUG_PRINT1(c,x1) __DEBUG_PRINT1(c,x1)

#define __DEBUG_PRINT(c,string) printf(string)
#define DEBUG_PRINT(c) __DEBUG_PRINT(c)

#endif
